name: Python 3.10-3.13 Version Display Workflow

on:
  workflow_dispatch:

jobs:
  display_python_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Versions
        run: |
          python -V
