name: Hello World

on:
  workflow_dispatch:
    inputs:
      your_name:
        description: "あなたの名前を教えてください"
        required: true
        default: "Guest"

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      NAME: "${{ github.event.inputs.your_name }}"
    steps:
      - name: Say Hello
        run: echo "こんにちは、$NAME さん！"
